version: '3.2'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HTTP_HOST=http://nginx/
    volumes:
      - ./src:/var/www/html/src

  nginx:
    image: nginx:1.15.7-alpine
    volumes:
      - ./compose.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    ports:
      - 80:80
