version: '2.1'
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker-compose exec php ./vendor/bin/phpcs src --standard=PSR2