version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - setup_remote_docker
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
  checks:
    steps:
      - run: docker-compose exec php ./vendor/bin/phpcs src --standard=PSR2