version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: |
            docker-compose build --no-cache
      - run:
          name: Start Docker Compose
          command: docker-compose up -d

