version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Build Docker images
          command: |
            docker-compose build --no-cache
      - run:
          name: Start Docker Compose
          command: docker-compose up -d

